SELECT MAX(salary) FROM EMPLOYEE;
SELECT MIN(salary) FROM EMPLOYEE;
SELECT SUM(salary) FROM EMPLOYEE;
SELECT AVG(salary) FROM EMPLOYEE;
SELECT COUNT(salary) FROM EMPLOYEE;
SELECT LCASE(emp_name) FROM EMPLOYEE;
SELECT UCASE(emp_name) FROM EMPLOYEE;
SELECT MID(emp_name, 2, 3) FROM EMPLOYEE;

SELECT MAX(salary) FROM TE;
SELECT MIN(salary) FROM TE;
SELECT SUM(salary) FROM TE;
SELECT AVG(salary) FROM TE;
SELECT COUNT(salary) FROM TE;
SELECT LCASE(emp_name) FROM TE;
SELECT UCASE(emp_name) FROM TE;
SELECT MID(emp_name, 2, 3) FROM TE;