CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6),
    NAME VARCHAR(20),
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE INT,
    STATE VARCHAR(15),
    BALDUE DECIMAL(10,2)
);


CREATE TABLE PRODUCT_MASTER (
    PRODUCTNO VARCHAR(6),
    DESCRIPTION VARCHAR(15),
    PROFITPERCENT DECIMAL(4,2),
    UNITMEASURE VARCHAR(10),
    QTYONHAND INT,
    REORDERLVL INT,
    SELLPRICE DECIMAL(10,2),
    COSTPRICE DECIMAL(10,2)
);

CREATE TABLE SALESMAN_MASTER (
    SALESMANNO VARCHAR(6),
    SALESMANNAME VARCHAR(20),
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(20),
    PINCODE INT,
    STATE VARCHAR(20),
    SALAMT DECIMAL(10,2),
    TGTTOGET DECIMAL(10,2),
    YTDSALES DECIMAL(10,2),
    REMARKS VARCHAR(60)
);
