DELETE FROM SALESMAN_MASTER
WHERE SALAMT = 3500;

SELECT * FROM SALESMAN_MASTER;

DELETE FROM PRODUCT_MASTER
WHERE QTYONHAND = 100;

SELECT * FROM PRODUCT_MASTER;

DELETE FROM CLIENT_MASTER
WHERE STATE = 'Tamil Nadu';

SELECT * FROM CLIENT_MASTER;
