SELECT NAME FROM CLIENT_MASTER;

SELECT * FROM CLIENT_MASTER;

SELECT NAME, CITY, STATE FROM CLIENT_MASTER;

SELECT DESCRIPTION FROM PRODUCT_MASTER;

SELECT * FROM CLIENT_MASTER
WHERE CITY = 'Mumbai';

SELECT SALESMANNAME FROM SALESMAN_MASTER
WHERE SALAMT = 3000;
