UPDATE CLIENT_MASTER
SET CITY = 'Bangalore'
WHERE CLIENTNO = 'C00005';

SELECT * FROM CLIENT_MASTER;

UPDATE CLIENT_MASTER
SET BALDUE = 1000
WHERE CLIENTNO = 'C00001';

SELECT * FROM CLIENT_MASTER;

UPDATE PRODUCT_MASTER
SET COSTPRICE = 950
WHERE DESCRIPTION = 'Trousers';

SELECT * FROM PRODUCT_MASTER;

UPDATE SALESMAN_MASTER
SET CITY = 'Pune';

SELECT * FROM SALESMAN_MASTER;
